version: '3.9'
services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${MLFLOW_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

  # MLFlow
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.8.1
    environment:
      BACKEND_STORE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${MLFLOW_DB}
      ARTIFACT_ROOT: ${ARTIFACT_ROOT}
      GOOGLE_APPLICATION_CREDENTIALS: /credentials/credentials.json
    volumes:
      - ${GOOGLE_CREDENTIALS_PATH}:/credentials/credentials.json
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure
    command: mlflow server --host 0.0.0.0 --port 8000

  # Database Admin UI
  pgadmin:
    image: dpage/pgadmin4:7.8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SETUP_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_SETUP_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_SERVER_JSON_FILE: /servers.json
    ports:
      - "5000:80"
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/servers.json

    entrypoint: >
      /bin/sh -c "
      echo 'postgres:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}' > /tmp/pgpassfile;
      mkdir -m 700 -p /var/lib/pgadmin/storage/${PGADMIN_EMAIL_STORAGE};
      chown -R pgadmin:root /var/lib/pgadmin/storage/${PGADMIN_EMAIL_STORAGE};
      cp /tmp/pgpassfile /var/lib/pgadmin/storage/${PGADMIN_EMAIL_STORAGE}/;
      chmod 600 /var/lib/pgadmin/storage/${PGADMIN_EMAIL_STORAGE}/pgpassfile;
      /entrypoint.sh
      "

volumes:
  postgres_data:
  pgadmin-data:
